### ISSUE TITLE
Known issues document needed.

### ISSUE THREAD

**Issue by riaanvddool** [pyimreg/python-register#20]
We need a file that lists 'known issues'.

First candidate:
Image data should be double, otherwise strange things might happen.

**Comment by stefanv** [comment]
Maybe just create issues and label them appropriately?

On Fri, Sep 9, 2011 at 1:39 AM, Riaan van den Dool
reply@reply.github.com
wrote:

**Comment by nfaggian** [comment]
Agree - all fixes need a ticket and associated pull requests
On Sep 13, 2011 7:57 AM, "Stefan van der Walt" <
reply@reply.github.com>
wrote:

**Comment by riaanvddool** [comment]
I am confused. :( Does this mean we all have to fork the project?

Riaan

On Tue, Sep 13, 2011 at 12:51 AM, Nathan Faggian
reply@reply.github.com
wrote:

**Comment by nfaggian** [comment]
Hi,

I think when I started using github I went about it the wrong way.

Basically I think we should adopt the push/pull model, so each of us
clone and submit a pull-request for changes.

I don't expect anything to really change - instead of making a branch
on the shared repo we would just clone and issue pull requests.
Ideally not pulling our own changes in, which forces us to review each
others code and discuss the best approach for things.

Hope this isn't too much of a nuisance.

-N

On 13 September 2011 16:53, Riaan van den Dool
reply@reply.github.com
wrote:

**Comment by stefanv** [comment]
On Tue, Sep 13, 2011 at 9:15 AM, Nathan Faggian
reply@reply.github.com
wrote:

> Basically I think we should adopt the push/pull model, so each of us
> clone and submit a pull-request for changes.
> 
> I don't expect anything to really change - instead of making a branch
> on the shared repo we would just clone and issue pull requests.
> Ideally not pulling our own changes in, which forces us to review each
> others code and discuss the best approach for things.
> 
> Hope this isn't too much of a nuisance.

We use this model with scikits.image as well.  It's pretty easy now
that GitHub allows you to automatically merge requests.

The important thing is never to work on a feature in your master
branch.  The master branch should always track the main repo.

**Comment by riaanvddool** [comment]
Closing this as it has become a bit irrelevant.
